import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { connect } from 'mongoose';
import { CONNECTION } from '@/app/db/db';

const inter = Inter({ subsets: ['latin'] });

// connect(CONNECTION).then(() => {
//   console.log('we are connected');
// });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
